name: Vault To AWS Secrets Sync
description: Synchonoze HashiCorp Vault Secrets to AWS Secrets Manager

inputs:
  filtered_secret_name:
    description: "Secret Name Filter (optional)"
    required: false
    default: ""
    type: string
  environment:
    description: "Target Environment"
    required: false
    default: "dev"
    type: string
  simulation_mode:
    description: "Simulation mode (no action performed)"
    required: false
    type: string
    default: "False"
  aws_replicated_regions:
    description: "AWS Replicated Regions"
    required: false
    default: ""
    type: string

runs:
  using: composite
  steps:
    - name: Vault To AWS Secrets Sync Script runs
      shell: sh
      env:
        AWS_FILTER_SECRET_NAME: ${{ inputs.filtered_secret_name }}
        AWS_REPLICATE_REGIONS:  ${{ inputs.aws_replicated_regions }}
        SIMULATION_MODE:        ${{ inputs.simulation_mode }}
        ENVIRONMENT:            ${{ inputs.environment }}
      run: |
        python ./scripts/aws_secrets_manager.py

        
        