name: Sync AWS Secrets

on:
  workflow_dispatch:

jobs:
  sync-aws-secrets:
    runs-on: ubuntu-latest

    #    permissions:
    #      contents: read
    #      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call secrets sync scipt
        shell: sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        run: |
          python scripts/aws_secrets_manager.py
