name: Test Action Variables
on:
  workflow_dispatch

jobs:
  print_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print some Variables
        shell: sh
        env:
          varx: 
        run: |
          echo "github.action_path: ${{github.action_path}}"
          echo "github.base_ref: ${{github.base_ref || 'BogusValue'}}"
          echo "github.event_path: ${{github.event_path}}"
          echo "github.ref: ${{github.ref}}"
          echo "github.ref_name: ${{github.ref_name}}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository Full Name: ${{ github.repository }}"
          echo "Repository Name: ${{ github.repository_name }}"
          echo "Full Ref: ${{ github.ref }}"
          echo "Branch Name: $(echo '${{ github.ref }}' | sed 's/refs\/heads\///')"



          