name: Vault to AWS Secrets Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: false
        type: choice
        options:
          - dev
          - uat
        default: dev
      simulation_mode:
        description: "Simulation mode (no action performed)"
        required: false
        type: choice
        options:
          - "True"
          - "False"
        default: "False"
      filtered_secret_name:
        description: "Secret Name Filter (optional)"
        required: false
        default: ""
        type: string

jobs:
  vault-to-aws-secrets-sync:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup AWS Authentication though GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume:         ${{ inputs.aws_role_to_assume }}
          aws-region:             ${{ inputs.aws_region }}
          role-session-name:      ${{ inputs.aws_role_session_name}}

      - name: 
        uses: ./.github/actions/vault_to_aws_secrets_sync
        with:
          aws_role_to_assume:     ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws_region:             ${{ vars.AWS_REGION }}
          aws_role_session_name:  ${{ github.run_id }}
          aws_replicated_regions: ${{ vars.AWS_REPLICATE_REGIONS || '' }}
          filtered_secret_name:   ${{ inputs.filtered_secret_name }}
          simulation_mode:        ${{ inputs.simulation_mode }}
          environment:            ${{ inputs.environment }}
